### PR TITLE
Pathfinding

### PR DESCRIPTION
**Pull request by pkage**
merge our work into master to work towards MVP demo

### CODE REVIEW

**Comment by stormwindy** [comment]
Can you give me quick notes of which file serves what purpose in the big picture and what has changed. Many files are marked to be completely new. However, some of them are refactoring of old ones, right?

**Comment by GavinPHR** [comment]
was it demonstrated on Friday that this is in fact minimally viable? which files do i need to run to see?

**Comment by smiltainis** [comment]
As we decided not to go with potential field planning only base.py is relevant and all the other files probably should not be merged on master.

**Comment by GavinPHR** [comment]
thanks for the comment, pull closed

**Pull request closed without merging**
